# Generated by Django 4.2.20 on 2025-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
