# Generated by Django 4.2.20 on 2025-04-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_user_first_name_alter_user_last_name'),
        ('hotelweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.user'),
        ),
    ]
